<?php

/**
 * @file
 * Contains xtools.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function xtools_help($route_name, RouteMatchInterface $route_match)
{
    switch ($route_name) {
        // Main module help for the xtools module.
        case 'help.page.xtools':
            $output = '';
            $output .= '<h3>' . t('About') . '</h3>';
            $output .= '<p>' . t('Xcono Core Module') . '</p>';
            return $output;

        default:
    }
}


/**
 * Implements hook_mail().
 */
function xtools_mail($key, &$message, $params)
{

    switch ($key) {

        case 'default':
            // note: $message['from'] is required, otherwise the email will not be sent
            // the only way in drupal 8 to set the from email address is to set it in the $message array
            $message['from'] = $message['from'] ?: \Drupal::config('system.site')->get('mail');
            $message['subject'] = $params['title'];
            $message['body'][] = Drupal\Component\Utility\Html::escape($params['message']);
            break;
    }
}
